services:

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8050:80"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ensures proper file watching in Docker
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  backend:
    build: 
      context: ./backend
    container_name: backend
    ports:
      - "8051:8051"
    volumes:
      - ./backend:/app
    restart: unless-stopped
