services:
  backend:
    build: 
      context: ./backend  # Path to your FastAPI backend code
    container_name: backend
    ports:
      - "8051:8051"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  react-frontend:
    build:
      context: ./frontend  # Path to your React frontend code
    container_name: react-frontend
    ports:
      - "8050:80"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Ensures proper file watching in Docker
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
